"""Seed default users for all roles (local/demo environments only).

Usage:
    cd backend && python -m scripts.seed_users
    cd backend && python -m scripts.seed_users --rotate-existing

Safe to re-run: existing accounts are skipped (never silently touched) unless
--rotate-existing is passed explicitly, in which case each already-existing
seeded account gets a freshly generated temporary password.

RC1 Phase 0 — Security Remediation (Finding 3): this script used to create
every seeded account (including admin) with the same hardcoded, committed
password ("Admin123!"), public to anyone with repo access — a permanent
full-privilege backdoor for any deployment ever seeded from it. It now:
  - generates one cryptographically random temporary password per user via
    app.core.security.generate_temporary_password(), the same helper
    POST /admin/users and the admin password-reset endpoint already use;
  - forces must_change_password=True on every seeded/rotated account, so
    the generated password can never become a standing credential;
  - refuses to run when ENVIRONMENT=production unless the operator
    explicitly sets SEED_USERS_ALLOW_PRODUCTION=yes;
  - never prints a password to stdout/logs — newly generated credentials
    are written once to a single local, gitignored file
    (backend/data/seed_users_credentials.local.txt), overwritten (not
    appended) on each run that issues new credentials, with a clear
    on-screen warning pointing at the file rather than the values.
"""
import os
import sys
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from app.config import settings
from app.database import SessionLocal
from app.models.auth import UserAccount
from app.core.security import hash_password, generate_temporary_password

SEED_USERS = [
    {
        "email": "admin@construction.ai",
        "full_name": "System Administrator",
        "role": "admin",
    },
    {
        "email": "executive@construction.ai",
        "full_name": "Ahmad Al-Rashidi",
        "role": "executive",
    },
    {
        "email": "pm@construction.ai",
        "full_name": "Khalid Al-Mansouri",
        "role": "project_manager",
    },
    {
        "email": "engineer@construction.ai",
        "full_name": "Mohammed Al-Zahrani",
        "role": "site_engineer",
    },
    {
        "email": "procurement@construction.ai",
        "full_name": "Fatima Al-Otaibi",
        "role": "procurement_officer",
    },
    {
        "email": "safety@construction.ai",
        "full_name": "Omar Al-Ghamdi",
        "role": "safety_quality_officer",
    },
]

CREDENTIALS_OUTPUT_PATH = Path(__file__).resolve().parent.parent / "data" / "seed_users_credentials.local.txt"


def _refuse_in_production() -> None:
    allow_override = os.environ.get("SEED_USERS_ALLOW_PRODUCTION", "").strip().lower() in ("1", "true", "yes")
    if settings.ENVIRONMENT == "production" and not allow_override:
        print(
            "Refusing to run scripts.seed_users with ENVIRONMENT=production.\n"
            "This creates/rotates demo accounts with newly generated temporary\n"
            "passwords — not something to run unattended against a real deployment.\n"
            "If this is genuinely intended, re-run with SEED_USERS_ALLOW_PRODUCTION=yes.",
            file=sys.stderr,
        )
        sys.exit(1)


def _write_credentials_file(issued: list[tuple[str, str]]) -> None:
    CREDENTIALS_OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Generated by scripts/seed_users.py -- local/demo use only. Never commit.",
        "# Each account below must change its password on first login",
        "# (must_change_password=True was set for all of them).",
        "",
    ]
    for email, password in issued:
        lines.append(f"{email}\t{password}")
    CREDENTIALS_OUTPUT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


def seed(rotate_existing: bool = False) -> None:
    _refuse_in_production()
    db = SessionLocal()
    issued: list[tuple[str, str]] = []
    try:
        created = 0
        skipped = 0
        rotated = 0
        for u in SEED_USERS:
            existing = db.query(UserAccount).filter(UserAccount.email == u["email"]).first()
            if existing:
                if not rotate_existing:
                    # Never silently touch an existing (possibly real,
                    # already-in-use) account's credentials on a plain rerun.
                    print(f"  SKIP  {u['email']} (already exists, role={existing.role})")
                    skipped += 1
                    continue
                temp_password = generate_temporary_password()
                existing.hashed_password = hash_password(temp_password)
                existing.must_change_password = True
                existing.failed_login_attempts = 0
                existing.locked_until = None
                issued.append((u["email"], temp_password))
                rotated += 1
                print(f"  ROTATE {u['email']} (role={existing.role})")
                continue
            temp_password = generate_temporary_password()
            user = UserAccount(
                email=u["email"],
                hashed_password=hash_password(temp_password),
                full_name=u["full_name"],
                role=u["role"],
                is_active=True,
                must_change_password=True,
            )
            db.add(user)
            issued.append((u["email"], temp_password))
            created += 1
            print(f"  CREATE {u['email']} (role={u['role']})")
        db.commit()
        print(f"\nDone: {created} created, {rotated} rotated, {skipped} skipped.")
        if issued:
            _write_credentials_file(issued)
            print(
                f"\nWARNING: {len(issued)} newly generated temporary password(s) were "
                f"written to:\n  {CREDENTIALS_OUTPUT_PATH}\n"
                "That file is gitignored and is overwritten every time this script "
                "issues new credentials. Distribute the passwords from it and then "
                "delete it -- each account must change its password on first login."
            )
    finally:
        db.close()


if __name__ == "__main__":
    seed(rotate_existing="--rotate-existing" in sys.argv[1:])
